### ISSUE TITLE
Feature request: Add buildpacks build method

### ISSUE THREAD

**Issue by scart88** [rails/mrsk#1]
Congratulations on starting this fantastic and very long waited method to deploy Rails apps!!! 🥇 

I would like to have a way to build the images using [pack](https://buildpacks.io/docs/tools/pack/) and `buildpacks`.

Sometimes is more straightforward than using the Dockerfile as it just works. 

Of course, I'm not sure what the plans are for this beautiful gem, but I would like to start with a few ideas. 

Having multiple ways to build the image would give more freedom to anyone to build the docker/cloudnative images however they want.

**Comment by dhh** [comment]
Thanks! Exciting for it. I'm building this for containers specifically. Don't want to go down the buildpack route. Understand why some approaches went there, but I think we can get to the same destination without that additional abstraction. Rails 7.1 will ship with a default Dockerfile. This works with that.

**Comment by schneems** [comment]
I know this is an old issue but wanted to drop in and possibly clear up some confusion. It doesn’t need to be re-opened or anything, I’m just asking for the chance to clear stuff up, possibly answer questions that might come along.

> I'm building this for containers specifically. 

FWIW Cloud Native Buildpacks are a project from CNCF and generate containers (OCI images). The largest purveyor of CNBs right now is paketo https://paketo.io.

CNB is an open spec (versus Heroku’s proprietary one) and are essentially an alternative to Dockerfile, here’s a tutorial showing how it works to build an image that you then run with Docker CLI. https://www.schneems.com/2024/05/01/build-a-ruby-on-rails-application-image-in-5-minutes-no-dockerfile-required/

I need to update it to Ubuntu 24.04 and docker’s support of invoking platform specific containers (the latest Buildpacks target x86 (AMD) as well as ARM). But the general idea is all right there.

The primary benefit of CNBs for whoever is writing and maintaining them (versus dockerfile) is a lower level layer API so you can do things like cache manipulation without having to resort to things like “line buddies” https://jkutner.github.io/2021/04/26/write-good-dockerfile.html. There’s also an ecosystem around them similar to rubygems so you can depend on another buildpack and it’s more like working with a library than working with codegen (like the old auth libraries before devise). 

Functionally the main difference would be calling “pack build” versus “docker build”.
