### ISSUE TITLE
Support for multiple env?

### ISSUE THREAD

**Issue by chrisdebruin** [rails/mrsk#14]
@dhh Thanks for the gem, looks promising. Are there any plans to support multiple env like `staging` and `production`? 

Would be nice to run `mrsk deploy staging` and `mrsk deploy production`

**Comment by dhh** [comment]
Just added that: https://github.com/rails/mrsk/commit/9a84460754cf771532935dc0728615a6424253e7

You can have multiple destinations with their own config that gets merged in. Will add some docs for it shortly 👍

**Comment by chrisdebruin** [comment]
awesome, thnx
