### ISSUE TITLE
Support for scaling?

### ISSUE THREAD

**Issue by chrisdebruin** [rails/mrsk#16]
Are there any plans for adding support to scale containers (on the same host) up and down? Something you can do with docker-compose for example `docker-compose up -d --scale service=2`

As far as I can see traefik already supports this. Not sure if this is the direction you want to go.

Thanks, keep up the good work

**Comment by chrisdebruin** [comment]
Ok. I thought the general idea with docker was to run a single process and don't do forks when running container. Instead you would run container with `WEB_CONCURRENCY=1`. If you need more workers you just spinup more containers

**Comment by dhh** [comment]
Needlessly complicated with no payback. Totally fine to run multiple sub processes of the same overall process.
