### ISSUE TITLE
Rename app VERSION concept to TAG

### ISSUE THREAD

**Issue by fschueller** [rails/mrsk#32]
While playing with rollback, I found the terminology of VERSION quite confusing.

The concept of the rollback is based on the image _tag_, such as

> [snip from README]
> ```
> App Host: 192.168.0.1
> CONTAINER ID   IMAGE                                                                         COMMAND                  CREATED          STATUS                      PORTS      NAMES
> 1d3c91ed1f51   registry.digitalocean.com/user/app:6ef8a6a84c525b123c5245345a8483f86d05a123   "/rails/bin/docker-e…"   19 minutes ago   Up 19 minutes               3000/tcp   chat-6ef8a6a84c525b123c5245345a8483f86d05a123
> 539f26b28369   registry.digitalocean.com/user/app:e5d9d7c2b898289dfbc5f7f1334140d984eedae4   "/rails/bin/docker-e…"   31 minutes ago   Exited (1) 27 minutes ago              chat-e5d9d7c2b898289dfbc5f7f1334140d984eedae4
> ```
> From the example above, we can see that **`e5d9d7c2b898289dfbc5f7f1334140d984eedae4`** was the last version, so it's available as a rollback target.
> [/snip]

While the tag can represent the app's version, in this case there's semantically no thing like a container version. Changing it to tag will align this to Docker's (or in general, container) terminology and cause less confusion around what's meant by this. Note that this is mainly a cosmetic change, but could help understand what's actually being targeted a lot.

**Comment by dhh** [comment]
The actual mechanics of the rollback use the passed version to construct the name of the container, not the tag for it. We should document the distinction better 👍
