### ISSUE TITLE
A few questions about Docker internal network, Rails migrations and Sidekiq workers

### ISSUE THREAD

**Issue by scart88** [rails/mrsk#4]
1. What would be the best way to run `rails db:migrate` or `wait/abort` if there are pending migrations?
2. What would be the best way to run multiple Sidekiq workers?
3. Should all containers run under the same bridge network? This way, the containers can communicate in an internal network, and it would be much easier to access the DB (PostgreSQL) from a docker container.

**Comment by dhh** [comment]
Yes! Want to solve all these issues. Have something in mind for workers and migration shortly.

**Comment by milushov** [comment]
Hey @dhh, any news on the best way to run rails `db:migrate`?

**Comment by krtschmr** [comment]
Hey @dhh , it's still hard to find info about the best way to have `rails db:migrate` executed during `kamal deploy`. What's best practice?

**Comment by dhh** [comment]
For Rails apps, use the bin/docker-entrypoint, it's built-in to new Rails apps now. Just generate a new app and see how the default Dockerfile and entrypoint work together.
