### ISSUE TITLE
Configuration file required even when running `rake mrsk:init`

### ISSUE THREAD

**Issue by tonysm** [rails/mrsk#5]
Hey, I was trying to test this out and got an error when running `./bin/rake mrsk:init`:

```bash
bundle add mrsk

./bin/rake mrsk:init  
rake aborted!
Configuration file not found in /home/tony/Code/docker-rails/config/deploy.yml
/home/tony/Code/docker-rails/Rakefile:6:in `<main>'
(See full trace by running task with --trace)
```

It looks like the `Configuration.load_file()` call [here](https://github.com/rails/mrsk/blob/main/lib/tasks/mrsk/setup.rb#L6) is what breaks based on the `load_file` implementation [here](https://github.com/rails/mrsk/blob/fe52ce654746bc5d5b739396d33a13b708c21ed5/lib/mrsk/configuration.rb#L7-L13) (I don't know much about building gems).

Is there a way to only require the file when running any of the `mrsk` commands? Or do we need to restructure the Configuration class so it lazily loads the file?

Btw, I was able to bypass this by creating the stub file manually.

**Comment by dhh** [comment]
Thanks for reporting! Temporary fix in place via 1609b43ef88cd4985026c18475bddfcdc7df3c64
